services:
  postgres:
    image: postgres
    container_name: schman
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - schman-vol:/usr/local/pgsql/data

volumes:
  schman-vol:
    external: true